version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "5433:5432"

  orderservice:
    build:
      context: ./OrderService
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - MT_LICENSE=free
      - ConnectionStrings__PostgreSqlConnection=Host=postgres;Database=OrderDb;Username=postgres;Password=${DB_PASSWORD}
      - RabbitMQHost=rabbitmq

  inventoryservice:
    build:
      context: ./InventoryService
      dockerfile: Dockerfile
    ports:
      - "5002:8080"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - MT_LICENSE=free
      - ConnectionStrings__PostgreSqlConnection=Host=postgres;Database=InventoryDb;Username=postgres;Password={DB_PASSWORD}
      - RabbitMQHost=rabbitmq